"""added new table clients

Revision ID: 002c17453b62
Revises: 66e4e43f5f97
Create Date: 2024-09-16 09:10:07.630273

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "002c17453b62"
down_revision = "66e4e43f5f97"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("inn", sa.String(length=20), nullable=False),
        sa.Column("ogrn", sa.String(length=20), nullable=False),
        sa.Column("kpp", sa.String(length=20), nullable=True),
        sa.Column("address", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("signer", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("client_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "clients", ["client_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("client_id")

    op.drop_table("clients")
    # ### end Alembic commands ###
