"""added new table schedules

Revision ID: 0c6e441d106d
Revises: 3a1ddf46748d
Create Date: 2024-08-22 10:14:06.513434

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c6e441d106d"
down_revision = "3a1ddf46748d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calculate_result_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("calc_id", sa.Integer(), nullable=False),
        sa.Column("leas_payment_amount", sa.Float(), nullable=False),
        sa.Column("early_repayment_amount", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["calc_id"],
            ["leas_calculator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calculate_result_schedules")
    # ### end Alembic commands ###
