"""added new table Sellers

Revision ID: 10e362e2f46c
Revises: b438c54b1b6b
Create Date: 2024-09-03 17:11:27.434263

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10e362e2f46c"
down_revision = "b438c54b1b6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sellers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("inn", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(sa.Column("seller_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "sellers", ["seller_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("seller_id")

    op.drop_table("sellers")
    # ### end Alembic commands ###
