"""added new columns increase_rate_str

Revision ID: 120a2bbc71e9
Revises: fbdd2230c853
Create Date: 2024-11-02 16:41:07.024409

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "120a2bbc71e9"
down_revision = "fbdd2230c853"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("main_annuity", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("increase_rate_str", sa.String(length=255), nullable=False)
        )

    with op.batch_alter_table("main_differentiated", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("increase_rate_str", sa.String(length=255), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("main_differentiated", schema=None) as batch_op:
        batch_op.drop_column("increase_rate_str")

    with op.batch_alter_table("main_annuity", schema=None) as batch_op:
        batch_op.drop_column("increase_rate_str")

    # ### end Alembic commands ###
