"""added new columns in Seller

Revision ID: 13983b448ee9
Revises: 281cdfb28d9a
Create Date: 2024-09-09 12:39:39.146750

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13983b448ee9"
down_revision = "281cdfb28d9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sellers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ogrn", sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column("address", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("phone", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("signer", sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ["ogrn"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sellers", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("signer")
        batch_op.drop_column("phone")
        batch_op.drop_column("address")
        batch_op.drop_column("ogrn")

    # ### end Alembic commands ###
