"""Updeted LeasCulc table

Revision ID: 27ddcd9de88b
Revises: 81f6a8785260
Create Date: 2024-07-29 13:46:51.668783

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "27ddcd9de88b"
down_revision = "81f6a8785260"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tranches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("tranche_1_size", sa.Float(), nullable=True),
        sa.Column("tranche_1_rate", sa.Float(), nullable=True),
        sa.Column("tranche_1_fee", sa.Float(), nullable=True),
        sa.Column("tranche_1_own_fee", sa.Float(), nullable=True),
        sa.Column("tranche_1_credit_date", sa.Date(), nullable=True),
        sa.Column("tranche_1_payment_date", sa.Date(), nullable=True),
        sa.Column("tranche_2_size", sa.Float(), nullable=True),
        sa.Column("tranche_2_rate", sa.Float(), nullable=True),
        sa.Column("tranche_2_fee", sa.Float(), nullable=True),
        sa.Column("tranche_2_own_fee", sa.Float(), nullable=True),
        sa.Column("tranche_2_credit_date", sa.Date(), nullable=True),
        sa.Column("tranche_2_payment_date", sa.Date(), nullable=True),
        sa.Column("tranche_3_size", sa.Float(), nullable=True),
        sa.Column("tranche_3_rate", sa.Float(), nullable=True),
        sa.Column("tranche_3_fee", sa.Float(), nullable=True),
        sa.Column("tranche_3_own_fee", sa.Float(), nullable=True),
        sa.Column("tranche_3_credit_date", sa.Date(), nullable=True),
        sa.Column("tranche_3_payment_date", sa.Date(), nullable=True),
        sa.Column("tranche_4_size", sa.Float(), nullable=True),
        sa.Column("tranche_4_rate", sa.Float(), nullable=True),
        sa.Column("tranche_4_fee", sa.Float(), nullable=True),
        sa.Column("tranche_4_own_fee", sa.Float(), nullable=True),
        sa.Column("tranche_4_credit_date", sa.Date(), nullable=True),
        sa.Column("tranche_4_payment_date", sa.Date(), nullable=True),
        sa.Column("tranche_5_size", sa.Float(), nullable=True),
        sa.Column("tranche_5_rate", sa.Float(), nullable=True),
        sa.Column("tranche_5_fee", sa.Float(), nullable=True),
        sa.Column("tranche_5_own_fee", sa.Float(), nullable=True),
        sa.Column("tranche_5_credit_date", sa.Date(), nullable=True),
        sa.Column("tranche_5_payment_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(sa.Column("currency", sa.String(length=10), nullable=True))
        batch_op.add_column(
            sa.Column("foreign_price", sa.Numeric(precision=10, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "initial_payment", sa.Numeric(precision=10, scale=2), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("credit_sum", sa.Numeric(precision=10, scale=2), nullable=True)
        )
        batch_op.add_column(sa.Column("credit_term", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("bank_commission", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("insurance_casko", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("insurance_osago", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("health_insurance", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("other_insurance", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("agent_commission", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("manager_bonus", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("tracker", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("mayak", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("fedresurs", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("gsm", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("mail", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("input_period", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("trance_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "tranches", ["trance_id"], ["id"])
        batch_op.drop_column("term")
        batch_op.drop_column("interest_rate")
        batch_op.drop_column("prepaid_expense")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "prepaid_expense",
                sa.NUMERIC(precision=10, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "interest_rate",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("term", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("trance_id")
        batch_op.drop_column("input_period")
        batch_op.drop_column("mail")
        batch_op.drop_column("gsm")
        batch_op.drop_column("fedresurs")
        batch_op.drop_column("mayak")
        batch_op.drop_column("tracker")
        batch_op.drop_column("manager_bonus")
        batch_op.drop_column("agent_commission")
        batch_op.drop_column("other_insurance")
        batch_op.drop_column("health_insurance")
        batch_op.drop_column("insurance_osago")
        batch_op.drop_column("insurance_casko")
        batch_op.drop_column("bank_commission")
        batch_op.drop_column("credit_term")
        batch_op.drop_column("credit_sum")
        batch_op.drop_column("initial_payment")
        batch_op.drop_column("foreign_price")
        batch_op.drop_column("currency")

    op.drop_table("tranches")
    # ### end Alembic commands ###
