"""added new column group_id

Revision ID: 281cdfb28d9a
Revises: de38610c7157
Create Date: 2024-09-06 09:24:44.319845

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "281cdfb28d9a"
down_revision = "de38610c7157"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.drop_column("group_id")

    # ### end Alembic commands ###
