"""added new property

Revision ID: 28348cb60190
Revises: 9a7470e090b9
Create Date: 2024-09-17 10:42:44.679930

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "28348cb60190"
down_revision = "9a7470e090b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("banks", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["inn"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("banks", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
