"""updated name

Revision ID: 300fffd79d33
Revises: 724f3b8bee1e
Create Date: 2024-07-16 09:36:24.866718

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "300fffd79d33"
down_revision = "724f3b8bee1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leas_calculator",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("manager_login", sa.String(length=200), nullable=False),
        sa.Column("deal_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("leas_calendar")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leas_calendar",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column(
            "manager_login", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
        sa.Column("deal_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name="leas_calendar_deal_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="leas_calendar_pkey"),
    )
    op.drop_table("leas_calculator")
    # ### end Alembic commands ###
