"""deleted user_icon to Deal

Revision ID: 397b901b3875
Revises: f9238f9980d7
Create Date: 2024-10-31 13:03:08.450039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397b901b3875'
down_revision = 'f9238f9980d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('created_by_icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_icon', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
