"""added abbreviation to Users

Revision ID: 3bb1f6384821
Revises: bfc08e10f1f1
Create Date: 2024-10-31 11:29:25.333695

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3bb1f6384821"
down_revision = "bfc08e10f1f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("abbreviation_name", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("abbreviation_name")

    # ### end Alembic commands ###
