"""added user_id to Deal

Revision ID: 3c231ce74928
Revises: 397b901b3875
Create Date: 2024-10-31 15:11:24.012139

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3c231ce74928"
down_revision = "397b901b3875"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_by", sa.String(length=50), nullable=False)
        )
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("created_by")

    # ### end Alembic commands ###
