"""added new columns allocates

Revision ID: 3d9af4432d4d
Revises: e2bfbc18cffa
Create Date: 2024-08-20 16:29:51.342137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9af4432d4d'
down_revision = 'e2bfbc18cffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leas_calculator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocate_vat', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('allocate_deposit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('allocate_redemption', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leas_calculator', schema=None) as batch_op:
        batch_op.drop_column('allocate_redemption')
        batch_op.drop_column('allocate_deposit')
        batch_op.drop_column('allocate_vat')

    # ### end Alembic commands ###
