"""Updeted LeasCulc table 2

Revision ID: 4118c688b2f3
Revises: 27ddcd9de88b
Create Date: 2024-07-29 14:29:49.178109

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4118c688b2f3"
down_revision = "27ddcd9de88b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tranches", schema=None) as batch_op:
        batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tranches", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "name", sa.VARCHAR(length=500), autoincrement=False, nullable=False
            )
        )

    # ### end Alembic commands ###
