"""added director to Client

Revision ID: 43dd2a7ad3e7
Revises: 120a2bbc71e9
Create Date: 2024-11-14 11:21:30.727637

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43dd2a7ad3e7"
down_revision = "120a2bbc71e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.add_column(sa.Column("director", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.drop_column("director")

    # ### end Alembic commands ###
