"""added new schedules

Revision ID: 4590caf1d56c
Revises: e9a189869fee
Create Date: 2024-10-18 09:38:36.515627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4590caf1d56c'
down_revision = 'e9a189869fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_annuity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calc_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('leas_payment_amount', sa.Float(), nullable=False),
    sa.Column('leas_payment_amount_str', sa.String(length=255), nullable=False),
    sa.Column('early_repayment_amount', sa.Float(), nullable=False),
    sa.Column('early_repayment_amount_str', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['calc_id'], ['leas_calculator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_differentiated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calc_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('leas_payment_amount', sa.Float(), nullable=False),
    sa.Column('leas_payment_amount_str', sa.String(length=255), nullable=False),
    sa.Column('early_repayment_amount', sa.Float(), nullable=False),
    sa.Column('early_repayment_amount_str', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['calc_id'], ['leas_calculator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_regression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calc_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('leas_payment_amount', sa.Float(), nullable=False),
    sa.Column('leas_payment_amount_str', sa.String(length=255), nullable=False),
    sa.Column('early_repayment_amount', sa.Float(), nullable=False),
    sa.Column('early_repayment_amount_str', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['calc_id'], ['leas_calculator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('calculate_result_schedules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculate_result_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('calc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leas_payment_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('early_repayment_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('leas_payment_amount_str', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('early_repayment_amount_str', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['calc_id'], ['leas_calculator.id'], name='calculate_result_schedules_calc_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='calculate_result_schedules_pkey')
    )
    op.drop_table('schedule_regression')
    op.drop_table('schedule_differentiated')
    op.drop_table('schedule_annuity')
    # ### end Alembic commands ###
