"""created a new table

Revision ID: 4a16b4c19da9
Revises: 7171403764f9
Create Date: 2024-08-19 14:01:01.680822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a16b4c19da9'
down_revision = '7171403764f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurance_casko_1', sa.Float(), nullable=True),
    sa.Column('insurance_casko_2', sa.Float(), nullable=True),
    sa.Column('insurance_casko_3', sa.Float(), nullable=True),
    sa.Column('insurance_casko_4', sa.Float(), nullable=True),
    sa.Column('insurance_casko_5', sa.Float(), nullable=True),
    sa.Column('insurance_osago_1', sa.Float(), nullable=True),
    sa.Column('insurance_osago_2', sa.Float(), nullable=True),
    sa.Column('insurance_osago_3', sa.Float(), nullable=True),
    sa.Column('insurance_osago_4', sa.Float(), nullable=True),
    sa.Column('insurance_osago_5', sa.Float(), nullable=True),
    sa.Column('health_insurance1', sa.Float(), nullable=True),
    sa.Column('health_insurance1_str', sa.Float(), nullable=True),
    sa.Column('health_insurance2', sa.Float(), nullable=True),
    sa.Column('health_insurance2_str', sa.String(length=255), nullable=True),
    sa.Column('health_insurance3', sa.Float(), nullable=True),
    sa.Column('health_insurance3_str', sa.String(length=255), nullable=True),
    sa.Column('health_insurance4', sa.Float(), nullable=True),
    sa.Column('health_insurance4_str', sa.String(length=255), nullable=True),
    sa.Column('health_insurance5', sa.Float(), nullable=True),
    sa.Column('health_insurance5_str', sa.String(length=255), nullable=True),
    sa.Column('other_insurance1', sa.Float(), nullable=True),
    sa.Column('other_insurance1_str', sa.String(length=255), nullable=True),
    sa.Column('other_insurance2', sa.Float(), nullable=True),
    sa.Column('other_insurance2_str', sa.String(length=255), nullable=True),
    sa.Column('other_insurance3', sa.Float(), nullable=True),
    sa.Column('other_insurance3_str', sa.String(length=255), nullable=True),
    sa.Column('other_insurance4', sa.Float(), nullable=True),
    sa.Column('other_insurance4_str', sa.String(length=255), nullable=True),
    sa.Column('other_insurance5', sa.Float(), nullable=True),
    sa.Column('other_insurance5_str', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leas_calculator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'insurances', ['insurance_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leas_calculator', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('insurance_id')

    op.drop_table('insurances')
    # ### end Alembic commands ###
