"""added new column date_ru

Revision ID: 4d4c1369bc86
Revises: e617381cc6fa
Create Date: 2024-07-16 16:58:22.654628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4c1369bc86'
down_revision = 'e617381cc6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leas_calculator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_ru', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leas_calculator', schema=None) as batch_op:
        batch_op.drop_column('date_ru')

    # ### end Alembic commands ###
