"""added new column decision

Revision ID: 55c8ee5e12c8
Revises: d3083c565537
Create Date: 2024-11-22 10:42:36.231186

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55c8ee5e12c8"
down_revision = "d3083c565537"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risk_departments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("decision", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risk_departments", schema=None) as batch_op:
        batch_op.drop_column("decision")

    # ### end Alembic commands ###
