"""added new column telegram

Revision ID: 5c2dd73ece7f
Revises: bc627ca39aa0
Create Date: 2024-10-21 14:41:55.733606

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c2dd73ece7f"
down_revision = "bc627ca39aa0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("telegram", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("telegram")

    # ### end Alembic commands ###
