"""added new column active session id

Revision ID: 6059549ed130
Revises: 5c2dd73ece7f
Create Date: 2024-10-22 11:26:01.383590

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6059549ed130"
down_revision = "5c2dd73ece7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("active_session_id", sa.String(length=36), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("active_session_id")

    # ### end Alembic commands ###
