"""added new column dl_number_windows

Revision ID: 636f0cd146a4
Revises: 0a4e7d845b37
Create Date: 2024-07-12 12:35:51.285506

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "636f0cd146a4"
down_revision = "0a4e7d845b37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("dl_number_windows", sa.String(length=20), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.drop_column("dl_number_windows")

    # ### end Alembic commands ###
