"""added new column in Seller

Revision ID: 66e4e43f5f97
Revises: 13983b448ee9
Create Date: 2024-09-10 11:01:06.295030

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "66e4e43f5f97"
down_revision = "13983b448ee9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sellers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sellers", schema=None) as batch_op:
        batch_op.drop_column("email")

    # ### end Alembic commands ###
