"""rename company_name --> title

Revision ID: 6a6b04595bf0
Revises: 90a8225b22ff
Create Date: 2024-06-03 17:33:47.805632

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6a6b04595bf0"
down_revision = "90a8225b22ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sa.String(length=200), nullable=False))
        batch_op.drop_column("company_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "company_name",
                sa.VARCHAR(length=200),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("title")

    # ### end Alembic commands ###
