"""added schedule_type

Revision ID: 6e8366c1fda8
Revises: cb312f7d97ff
Create Date: 2024-10-18 17:02:04.724862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8366c1fda8'
down_revision = 'cb312f7d97ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leas_calculator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leas_calculator', schema=None) as batch_op:
        batch_op.drop_column('schedule_type')

    # ### end Alembic commands ###
