"""added new column status in LeasCalc

Revision ID: 7002a62b6f1d
Revises: ef33f1bc5fc4
Create Date: 2024-10-22 17:57:36.008712

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7002a62b6f1d"
down_revision = "ef33f1bc5fc4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.alter_column(
            "status", existing_type=sa.VARCHAR(length=50), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.alter_column(
            "status", existing_type=sa.VARCHAR(length=50), nullable=False
        )

    # ### end Alembic commands ###
