"""changed leas_calc

Revision ID: 7171403764f9
Revises: e9217e31235c
Create Date: 2024-08-19 13:33:26.307834

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7171403764f9"
down_revision = "e9217e31235c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_payment_date", sa.Date(), nullable=True))
        batch_op.drop_column("other_insurance")
        batch_op.drop_column("health_insurance_str")
        batch_op.drop_column("other_insurance_str")
        batch_op.drop_column("health_insurance")
        batch_op.drop_column("insurance_casko")
        batch_op.drop_column("insurance_osago")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "insurance_osago",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "insurance_casko",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "health_insurance",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "other_insurance_str",
                sa.VARCHAR(length=50),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "health_insurance_str",
                sa.VARCHAR(length=50),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "other_insurance",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("first_payment_date")

    # ### end Alembic commands ###
