"""added new column decision icon

Revision ID: 7529e00325a5
Revises: 55c8ee5e12c8
Create Date: 2024-11-25 10:26:10.808023

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7529e00325a5"
down_revision = "55c8ee5e12c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risk_departments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("decision_icon", sa.String(length=100), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risk_departments", schema=None) as batch_op:
        batch_op.drop_column("decision_icon")

    # ### end Alembic commands ###
