"""deleted any columns

Revision ID: 7d4f65320b03
Revises: dcea4abbd312
Create Date: 2024-08-02 12:54:53.523680

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d4f65320b03"
down_revision = "dcea4abbd312"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.drop_column("insurance_osago_str")
        batch_op.drop_column("insurance_casko_str")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "insurance_casko_str",
                sa.VARCHAR(length=50),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "insurance_osago_str",
                sa.VARCHAR(length=50),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
