"""update leas_calc table

Revision ID: 8147199929c5
Revises: 4118c688b2f3
Create Date: 2024-08-01 14:40:22.226829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8147199929c5'
down_revision = '4118c688b2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leas_calculator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_condition', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leas_calculator', schema=None) as batch_op:
        batch_op.drop_column('item_condition')
        batch_op.drop_column('item_year')

    # ### end Alembic commands ###
