"""added new columns in leas_calc

Revision ID: 81f6a8785260
Revises: b76175284ea8
Create Date: 2024-07-18 09:57:54.213343

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "81f6a8785260"
down_revision = "b76175284ea8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("item_name", sa.String(length=500), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "prepaid_expense", sa.Numeric(precision=10, scale=2), nullable=True
            )
        )
        batch_op.add_column(sa.Column("term", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("interest_rate", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.drop_column("interest_rate")
        batch_op.drop_column("term")
        batch_op.drop_column("prepaid_expense")
        batch_op.drop_column("item_name")

    # ### end Alembic commands ###
