"""updeted leas_calc table

Revision ID: 88ff0c55fe48
Revises: 8147199929c5
Create Date: 2024-08-02 11:07:33.521369

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "88ff0c55fe48"
down_revision = "8147199929c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("initial_payment_percent", sa.Float(), nullable=True)
        )
        batch_op.add_column(sa.Column("credit_sum_percent", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.drop_column("credit_sum_percent")
        batch_op.drop_column("initial_payment_percent")

    # ### end Alembic commands ###
