"""update Deal

Revision ID: 90a8225b22ff
Revises: 640842fe23c0
Create Date: 2024-06-03 16:12:58.357322

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90a8225b22ff"
down_revision = "640842fe23c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("company_name", sa.String(length=200), nullable=False)
        )
        batch_op.add_column(
            sa.Column("company_inn", sa.String(length=20), nullable=False)
        )
        batch_op.add_column(
            sa.Column("created_by", sa.String(length=50), nullable=False)
        )
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.drop_column("title")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "title", sa.VARCHAR(length=200), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_column("created_at")
        batch_op.drop_column("created_by")
        batch_op.drop_column("company_inn")
        batch_op.drop_column("company_name")

    # ### end Alembic commands ###
