"""added new column item_price_str

Revision ID: a2f82de2e891
Revises: e74949246f0b
Create Date: 2024-07-17 12:35:48.259627

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a2f82de2e891"
down_revision = "e74949246f0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("item_price_str", sa.String(length=50), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.drop_column("item_price_str")

    # ### end Alembic commands ###
