"""fix user table

Revision ID: b11749941bb0
Revises: 887495d7e797
Create Date: 2024-06-03 14:26:29.180513

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b11749941bb0"
down_revision = "887495d7e797"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deal")
    op.drop_table("deal_steps")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=200),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True,
        )

    op.create_table(
        "deal_steps",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("step1_approved", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "step1_time", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "step1_user", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("step2_approved", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "step2_time", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "step2_user", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("step3_approved", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "step3_time", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "step3_user", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="deal_steps_pkey"),
    )
    op.create_table(
        "deal",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="deal_pkey"),
    )
    # ### end Alembic commands ###
