"""added new columns

Revision ID: b438c54b1b6b
Revises: 0d6b6c6a1ea8
Create Date: 2024-08-29 11:50:29.321719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b438c54b1b6b'
down_revision = '0d6b6c6a1ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculate_result_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leas_payment_amount_str', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('early_repayment_amount_str', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculate_result_schedules', schema=None) as batch_op:
        batch_op.drop_column('early_repayment_amount_str')
        batch_op.drop_column('leas_payment_amount_str')

    # ### end Alembic commands ###
