"""added new table

Revision ID: b4d36ab23827
Revises: 6e8366c1fda8
Create Date: 2024-10-20 12:09:14.009960

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b4d36ab23827"
down_revision = "6e8366c1fda8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commercial_offers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("leas_calculator_id", sa.Integer(), nullable=True),
        sa.Column("type_of_schedule", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["leas_calculator_id"],
            ["leas_calculator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("commercial_offers")
    # ### end Alembic commands ###
