"""added new column date of reg for Seller and Clients

Revision ID: ba336fe11b6b
Revises: 28348cb60190
Create Date: 2024-09-17 11:00:48.648690

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba336fe11b6b"
down_revision = "28348cb60190"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.add_column(sa.Column("date_of_registration", sa.Date(), nullable=True))

    with op.batch_alter_table("sellers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("date_of_registration", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sellers", schema=None) as batch_op:
        batch_op.drop_column("date_of_registration")

    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.drop_column("date_of_registration")

    # ### end Alembic commands ###
