"""added new columns in the main

Revision ID: bc627ca39aa0
Revises: b4d36ab23827
Create Date: 2024-10-21 11:42:42.738551

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc627ca39aa0"
down_revision = "b4d36ab23827"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("main_annuity", schema=None) as batch_op:
        batch_op.add_column(sa.Column("redemption_value", sa.Float(), nullable=False))
        batch_op.add_column(
            sa.Column("redemption_value_str", sa.String(length=255), nullable=False)
        )
        batch_op.add_column(
            sa.Column("transaction_processing_fee", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "transaction_processing_fee_str", sa.String(length=255), nullable=False
            )
        )
        batch_op.add_column(sa.Column("company_margin", sa.Float(), nullable=False))
        batch_op.add_column(
            sa.Column("company_margin_str", sa.String(length=255), nullable=False)
        )
        batch_op.add_column(sa.Column("effective_rate", sa.Float(), nullable=False))
        batch_op.add_column(
            sa.Column("effective_rate_str", sa.String(length=255), nullable=False)
        )

    with op.batch_alter_table("main_differentiated", schema=None) as batch_op:
        batch_op.add_column(sa.Column("redemption_value", sa.Float(), nullable=False))
        batch_op.add_column(
            sa.Column("redemption_value_str", sa.String(length=255), nullable=False)
        )
        batch_op.add_column(
            sa.Column("transaction_processing_fee", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "transaction_processing_fee_str", sa.String(length=255), nullable=False
            )
        )
        batch_op.add_column(sa.Column("company_margin", sa.Float(), nullable=False))
        batch_op.add_column(
            sa.Column("company_margin_str", sa.String(length=255), nullable=False)
        )
        batch_op.add_column(sa.Column("effective_rate", sa.Float(), nullable=False))
        batch_op.add_column(
            sa.Column("effective_rate_str", sa.String(length=255), nullable=False)
        )

    with op.batch_alter_table("main_regression", schema=None) as batch_op:
        batch_op.add_column(sa.Column("redemption_value", sa.Float(), nullable=False))
        batch_op.add_column(
            sa.Column("redemption_value_str", sa.String(length=255), nullable=False)
        )
        batch_op.add_column(
            sa.Column("transaction_processing_fee", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "transaction_processing_fee_str", sa.String(length=255), nullable=False
            )
        )
        batch_op.add_column(sa.Column("company_margin", sa.Float(), nullable=False))
        batch_op.add_column(
            sa.Column("company_margin_str", sa.String(length=255), nullable=False)
        )
        batch_op.add_column(sa.Column("effective_rate", sa.Float(), nullable=False))
        batch_op.add_column(
            sa.Column("effective_rate_str", sa.String(length=255), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("main_regression", schema=None) as batch_op:
        batch_op.drop_column("effective_rate_str")
        batch_op.drop_column("effective_rate")
        batch_op.drop_column("company_margin_str")
        batch_op.drop_column("company_margin")
        batch_op.drop_column("transaction_processing_fee_str")
        batch_op.drop_column("transaction_processing_fee")
        batch_op.drop_column("redemption_value_str")
        batch_op.drop_column("redemption_value")

    with op.batch_alter_table("main_differentiated", schema=None) as batch_op:
        batch_op.drop_column("effective_rate_str")
        batch_op.drop_column("effective_rate")
        batch_op.drop_column("company_margin_str")
        batch_op.drop_column("company_margin")
        batch_op.drop_column("transaction_processing_fee_str")
        batch_op.drop_column("transaction_processing_fee")
        batch_op.drop_column("redemption_value_str")
        batch_op.drop_column("redemption_value")

    with op.batch_alter_table("main_annuity", schema=None) as batch_op:
        batch_op.drop_column("effective_rate_str")
        batch_op.drop_column("effective_rate")
        batch_op.drop_column("company_margin_str")
        batch_op.drop_column("company_margin")
        batch_op.drop_column("transaction_processing_fee_str")
        batch_op.drop_column("transaction_processing_fee")
        batch_op.drop_column("redemption_value_str")
        batch_op.drop_column("redemption_value")

    # ### end Alembic commands ###
