"""added two new columns in leas_calc

Revision ID: bfc08e10f1f1
Revises: 7002a62b6f1d
Create Date: 2024-10-30 15:11:24.263688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc08e10f1f1'
down_revision = '7002a62b6f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leas_calculator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('differential_payment_increase_factor', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('months_regressive_payments', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leas_calculator', schema=None) as batch_op:
        batch_op.drop_column('months_regressive_payments')
        batch_op.drop_column('differential_payment_increase_factor')

    # ### end Alembic commands ###
