"""added new column in Deal

Revision ID: c5c5555fc3ab
Revises: c2d86cdb9cd1
Create Date: 2024-06-10 11:36:35.622517

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c5c5555fc3ab"
down_revision = "c2d86cdb9cd1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "name_without_special_symbols", sa.String(length=200), nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.drop_column("name_without_special_symbols")

    # ### end Alembic commands ###
