"""added new tables with main info

Revision ID: cb312f7d97ff
Revises: 4590caf1d56c
Create Date: 2024-10-18 15:48:44.619478

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb312f7d97ff"
down_revision = "4590caf1d56c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "main_annuity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("calc_id", sa.Integer(), nullable=False),
        sa.Column("lease_agreement_amount", sa.Float(), nullable=False),
        sa.Column("lease_agreement_amount_str", sa.String(length=255), nullable=False),
        sa.Column("vat_refund", sa.Float(), nullable=False),
        sa.Column("vat_refund_str", sa.String(length=255), nullable=False),
        sa.Column("save_income_tax", sa.Float(), nullable=False),
        sa.Column("save_income_tax_str", sa.String(length=255), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("total_cost_str", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["calc_id"],
            ["leas_calculator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "main_differentiated",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("calc_id", sa.Integer(), nullable=False),
        sa.Column("lease_agreement_amount", sa.Float(), nullable=False),
        sa.Column("lease_agreement_amount_str", sa.String(length=255), nullable=False),
        sa.Column("vat_refund", sa.Float(), nullable=False),
        sa.Column("vat_refund_str", sa.String(length=255), nullable=False),
        sa.Column("save_income_tax", sa.Float(), nullable=False),
        sa.Column("save_income_tax_str", sa.String(length=255), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("total_cost_str", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["calc_id"],
            ["leas_calculator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "main_regression",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("calc_id", sa.Integer(), nullable=False),
        sa.Column("lease_agreement_amount", sa.Float(), nullable=False),
        sa.Column("lease_agreement_amount_str", sa.String(length=255), nullable=False),
        sa.Column("vat_refund", sa.Float(), nullable=False),
        sa.Column("vat_refund_str", sa.String(length=255), nullable=False),
        sa.Column("save_income_tax", sa.Float(), nullable=False),
        sa.Column("save_income_tax_str", sa.String(length=255), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("total_cost_str", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["calc_id"],
            ["leas_calculator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("main_regression")
    op.drop_table("main_differentiated")
    op.drop_table("main_annuity")
    # ### end Alembic commands ###
