"""added new column archived_at (Deal)

Revision ID: cb8a2738709c
Revises: a0ce0fc5a485
Create Date: 2024-06-06 16:44:01.779716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8a2738709c'
down_revision = 'a0ce0fc5a485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
