"""added new column lkmb_commission in LeasCalc

Revision ID: d0ff44e14d70
Revises: 2bf85be7429e
Create Date: 2024-08-12 13:12:42.045709

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0ff44e14d70"
down_revision = "2bf85be7429e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lkmb_commission", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.drop_column("lkmb_commission")

    # ### end Alembic commands ###
