"""added new model Risk_department

Revision ID: d3083c565537
Revises: 43dd2a7ad3e7
Create Date: 2024-11-18 12:00:35.268399

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3083c565537"
down_revision = "43dd2a7ad3e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deal_id", sa.Integer(), nullable=False),
        sa.Column("decision_time", sa.DateTime(), nullable=True),
        sa.Column("responsible_person", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_departments")
    # ### end Alembic commands ###
