"""fixed column type

Revision ID: d52059a30349
Revises: 4a16b4c19da9
Create Date: 2024-08-19 14:17:31.558405

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d52059a30349"
down_revision = "4a16b4c19da9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("insurances", schema=None) as batch_op:
        batch_op.alter_column(
            "health_insurance1_str",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            type_=sa.String(length=255),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("insurances", schema=None) as batch_op:
        batch_op.alter_column(
            "health_insurance1_str",
            existing_type=sa.String(length=255),
            type_=sa.DOUBLE_PRECISION(precision=53),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
