"""added new columns in the leas_calc

Revision ID: dcea4abbd312
Revises: 88ff0c55fe48
Create Date: 2024-08-02 12:26:13.093144

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dcea4abbd312"
down_revision = "88ff0c55fe48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("foreign_price_str", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("initial_payment_str", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("credit_sum_str", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("insurance_casko_str", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("insurance_osago_str", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("health_insurance_str", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("other_insurance_str", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("tracker_str", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(sa.Column("mayak_str", sa.String(length=50), nullable=True))
        batch_op.add_column(
            sa.Column("fedresurs_str", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(sa.Column("gsm_str", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("mail_str", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.drop_column("mail_str")
        batch_op.drop_column("gsm_str")
        batch_op.drop_column("fedresurs_str")
        batch_op.drop_column("mayak_str")
        batch_op.drop_column("tracker_str")
        batch_op.drop_column("other_insurance_str")
        batch_op.drop_column("health_insurance_str")
        batch_op.drop_column("insurance_osago_str")
        batch_op.drop_column("insurance_casko_str")
        batch_op.drop_column("credit_sum_str")
        batch_op.drop_column("initial_payment_str")
        batch_op.drop_column("foreign_price_str")

    # ### end Alembic commands ###
