"""deleted phone column in Bank

Revision ID: e0d0350508f9
Revises: ba336fe11b6b
Create Date: 2024-09-18 12:55:56.919471

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e0d0350508f9"
down_revision = "ba336fe11b6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("banks", schema=None) as batch_op:
        batch_op.drop_column("phone")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("banks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "phone", sa.VARCHAR(length=20), autoincrement=False, nullable=True
            )
        )

    # ### end Alembic commands ###
