"""deleted some columns

Revision ID: e2bfbc18cffa
Revises: f5ab57294bb6
Create Date: 2024-08-19 16:14:11.906564

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2bfbc18cffa"
down_revision = "f5ab57294bb6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tranches", schema=None) as batch_op:
        batch_op.drop_column("tranche_3_payment_date")
        batch_op.drop_column("tranche_2_payment_date")
        batch_op.drop_column("tranche_1_payment_date")
        batch_op.drop_column("tranche_5_payment_date")
        batch_op.drop_column("tranche_4_payment_date")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tranches", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tranche_4_payment_date", sa.DATE(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "tranche_5_payment_date", sa.DATE(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "tranche_1_payment_date", sa.DATE(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "tranche_2_payment_date", sa.DATE(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "tranche_3_payment_date", sa.DATE(), autoincrement=False, nullable=True
            )
        )

    # ### end Alembic commands ###
