"""added new column in LeasCalculator

Revision ID: e617381cc6fa
Revises: 3c9dae5a619e
Create Date: 2024-07-16 09:45:22.222421

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e617381cc6fa"
down_revision = "3c9dae5a619e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("path_to_file", sa.String(length=500), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.drop_column("path_to_file")

    # ### end Alembic commands ###
