"""rename and add new column

Revision ID: e9217e31235c
Revises: c46b2592e0db
Create Date: 2024-08-15 16:46:21.642751

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e9217e31235c"
down_revision = "c46b2592e0db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("path_to_xlsx", sa.String(length=500), nullable=True)
        )
        batch_op.add_column(
            sa.Column("path_to_pdf", sa.String(length=500), nullable=True)
        )
        batch_op.drop_column("path_to_xlsx")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "path_to_file",
                sa.VARCHAR(length=500),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("path_to_pdf")
        batch_op.drop_column("path_to_xlsx")

    # ### end Alembic commands ###
