"""added new column Status (Deal)

Revision ID: ec04e43a5e0f
Revises: 6a6b04595bf0
Create Date: 2024-06-05 20:38:24.347621

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ec04e43a5e0f"
down_revision = "6a6b04595bf0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
