"""added new column status in LeasCalc

Revision ID: ef33f1bc5fc4
Revises: f8f878288c2a
Create Date: 2024-10-22 17:35:22.008011

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef33f1bc5fc4"
down_revision = "f8f878288c2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
