"""update item_price

Revision ID: efb454aa8cba
Revises: a2f82de2e891
Create Date: 2024-07-17 12:45:37.853542

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "efb454aa8cba"
down_revision = "a2f82de2e891"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.alter_column(
            "item_price",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=10, scale=2),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.alter_column(
            "item_price",
            existing_type=sa.Numeric(precision=10, scale=2),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
