"""added new column in users table

Revision ID: f00d67919859
Revises: c5c5555fc3ab
Create Date: 2024-07-09 08:59:46.752812

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f00d67919859"
down_revision = "c5c5555fc3ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fon_url", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("fon_url")

    # ### end Alembic commands ###
