"""added new column date_ru

Revision ID: f8f878288c2a
Revises: 6059549ed130
Create Date: 2024-10-22 13:29:09.167740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f878288c2a'
down_revision = '6059549ed130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_annuity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date_ru', sa.String(length=255), nullable=False))

    with op.batch_alter_table('schedule_differentiated', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date_ru', sa.String(length=255), nullable=False))

    with op.batch_alter_table('schedule_regression', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date_ru', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_regression', schema=None) as batch_op:
        batch_op.drop_column('payment_date_ru')

    with op.batch_alter_table('schedule_differentiated', schema=None) as batch_op:
        batch_op.drop_column('payment_date_ru')

    with op.batch_alter_table('schedule_annuity', schema=None) as batch_op:
        batch_op.drop_column('payment_date_ru')

    # ### end Alembic commands ###
