"""added user_icon to Deal

Revision ID: f9238f9980d7
Revises: 3bb1f6384821
Create Date: 2024-10-31 12:28:50.538052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9238f9980d7'
down_revision = '3bb1f6384821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_icon', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('created_by_icon')

    # ### end Alembic commands ###
