"""updated unique column in Bank

Revision ID: f98df3ac52f2
Revises: e0d0350508f9
Create Date: 2024-09-23 11:22:21.703450

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f98df3ac52f2"
down_revision = "e0d0350508f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("banks", schema=None) as batch_op:
        batch_op.drop_constraint("banks_inn_key", type_="unique")
        batch_op.create_unique_constraint(None, ["bic"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("banks", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_unique_constraint("banks_inn_key", ["inn"])

    # ### end Alembic commands ###
