"""renamed

Revision ID: f9d46fff6b2a
Revises: d52059a30349
Create Date: 2024-08-19 14:43:02.424911

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f9d46fff6b2a"
down_revision = "d52059a30349"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("insurances", schema=None) as batch_op:
        batch_op.add_column(sa.Column("insurance_casko1", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("insurance_casko2", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("insurance_casko3", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("insurance_casko4", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("insurance_casko5", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("insurance_osago1", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("insurance_osago2", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("insurance_osago3", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("insurance_osago4", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("insurance_osago5", sa.Float(), nullable=True))
        batch_op.drop_column("insurance_casko_1")
        batch_op.drop_column("insurance_osago_1")
        batch_op.drop_column("insurance_osago_3")
        batch_op.drop_column("insurance_osago_5")
        batch_op.drop_column("insurance_casko_2")
        batch_op.drop_column("insurance_casko_5")
        batch_op.drop_column("insurance_osago_4")
        batch_op.drop_column("insurance_casko_3")
        batch_op.drop_column("insurance_osago_2")
        batch_op.drop_column("insurance_casko_4")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("insurances", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "insurance_casko_4",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "insurance_osago_2",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "insurance_casko_3",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "insurance_osago_4",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "insurance_casko_5",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "insurance_casko_2",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "insurance_osago_5",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "insurance_osago_3",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "insurance_osago_1",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "insurance_casko_1",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("insurance_osago5")
        batch_op.drop_column("insurance_osago4")
        batch_op.drop_column("insurance_osago3")
        batch_op.drop_column("insurance_osago2")
        batch_op.drop_column("insurance_osago1")
        batch_op.drop_column("insurance_casko5")
        batch_op.drop_column("insurance_casko4")
        batch_op.drop_column("insurance_casko3")
        batch_op.drop_column("insurance_casko2")
        batch_op.drop_column("insurance_casko1")

    # ### end Alembic commands ###
