"""deleted first payment date

Revision ID: fa1bc802f99d
Revises: f98df3ac52f2
Create Date: 2024-10-14 11:24:35.039169

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa1bc802f99d"
down_revision = "f98df3ac52f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.drop_column("first_payment_date")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leas_calculator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "first_payment_date", sa.DATE(), autoincrement=False, nullable=True
            )
        )

    # ### end Alembic commands ###
