"""added new columns increase_rate_str

Revision ID: fbdd2230c853
Revises: 5b16225042f1
Create Date: 2024-11-02 16:17:49.587285

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fbdd2230c853"
down_revision = "5b16225042f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("main_regression", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("increase_rate_str", sa.String(length=255), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("main_regression", schema=None) as batch_op:
        batch_op.drop_column("increase_rate_str")

    # ### end Alembic commands ###
