name: CI

on:
  pull_request:
    branches:
      - deal
  push:
    branches:
      - deal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check formatting using Black
        run: black --check .

      - name: Lint with Ruff
        run: ruff check .
